import PublicLayout from "@/components/layouts/PublicLayout";
import Head from "next/head";

export default function Home() {
  return (
    <PublicLayout>
      <Head>
        <title>Nextjs fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Nextjs fullstack!</h1>
        <h2>Template</h2>
      </main>
    </PublicLayout>
  );
}
