import PublicLayout from "@/components/layouts/PublicLayout";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { FcGoogle } from "react-icons/fc";

export default function Signin() {
  return (
    <PublicLayout>
      <Head>
        <title>Nextjs fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-screen justify-center">
        <section className="w-full dark:bg-gray-900">
          <div className="mx-auto flex h-full flex-col items-center justify-center px-6 py-8 lg:py-0">
            <div className="w-full rounded-lg bg-white sm:max-w-md md:mt-0 xl:p-0">
              <div className="space-y-4 p-6 sm:p-8 md:space-y-6">
                <h1 className="text-center text-xl font-bold leading-tight tracking-tight text-gray-900 dark:text-white md:text-2xl">
                  Sign in to your account
                </h1>

                <button
                  className="flex w-full items-center justify-center space-x-2 rounded-md border p-2"
                  onClick={() =>
                    signIn("google", { callbackUrl: "/protected" })
                  }
                >
                  <FcGoogle /> <span>Sign in with Google</span>
                </button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </PublicLayout>
  );
}
